# lottopysite_uwsgi.ini file
[uwsgi]

# Django-related settings
# the base directory (full path)
chdir           = /home/williedynamite/projects/django_lottopy/django_lottopy
# Django's wsgi file
module          = lottopy_site.wsgi:application
# the virtualenv (full path)
#home            = /home/williedynamite/projects/django_lottopy/bin/activate

# process-related settings
# master
master          = true
# maximum number of worker processes
processes       = 10
# the socket (use the full path to be safe
socket          = /tmp/lottopysite.sock
# ... with appropriate permissions - may be needed
chmod-socket    = 664
# clear environment on exit
vacuum          = false
unset PYTHONPATH
unset PYTHONHOME
env = DJANGO_SETTINGS_MODULE=lottopy_site.settings