# Generated by Django 4.0 on 2022-06-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottopy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailmessage',
            options={'verbose_name': 'Emails to send', 'verbose_name_plural': 'Emails to send'},
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='attachment',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='send_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailmessage',
            name='users',
            field=models.ManyToManyField(to='lottopy.Subscribers'),
        ),
    ]
