# Generated by Django 4.0 on 2022-06-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottopy', '0002_alter_mailmessage_options_mailmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
